### ISSUE TITLE
Push To HaxeLib

### ISSUE THREAD

**Issue by cmandlbaur** [Glidias/haxevx#1]
Would be awesome if this was installable via haxelib.

**Comment by Glidias** [comment]
Would push to Haxelib once i start using it for actual production. As of now, it's only in draft stage.

**Comment by Glidias** [comment]
A pre-release installable is now on haxelib. 

`haxelib install haxevx`

User guide can be found on Wiki at github repository at the moment.

https://github.com/Glidias/haxevx/wiki/Vue---HaxeVX-Draft-version-guide
